services:
  bdd:
    container_name: bdd
    image: postgres:alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d test" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
  api:
    container_name: api
    build:
      context: .

    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=test
      - FRONT_URL=http=//localhost:4200
      - JWT_SECRET=azfuhvbakzjhvkvlkazvdckjlhvbkljhvazlrkkvlkazvdckjl
      - JWT_DURATION=86400000
    depends_on:
      - bdd
    links:
      - "bdd:database"
