services:
  bdd:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
  api:
    image: test
    restart: always
    ports:
      - 8080:8080
    environment:
      - BDD_USER=${POSTGRES_USER}
      - BDD_PASSWORD=${POSTGRES_PASSWORD}
      - BDD_DATABASE=${POSTGRES_DB}
      - FRONT_URL=${FRONT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_DURATION=${JWT_DURATION}
    depends_on:
      bdd:
        condition: service_healthy
    links:
      - "bdd:database"
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - bdd
    links:
      - "bdd:database"