name: Deploy to OVH VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to OVH VPS
      env:
        key: ${{ secrets.OVH_KEY }}
        ip: ${{ secrets.OVH_IP }}
      run: |
        echo $key > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh debian@$ip
        touch test.txt

